# Generated by Django 3.2 on 2022-12-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('club', models.CharField(blank=True, max_length=200)),
                ('call', models.CharField(blank=True, max_length=200)),
                ('qth', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email_public', models.EmailField(blank=True, max_length=200)),
                ('town', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('initial_chat', models.CharField(default='<p></p>', max_length=200)),
                ('beep_sound', models.BooleanField(default=False)),
                ('user_level', models.PositiveIntegerField(default=10)),
                ('list_rows', models.PositiveIntegerField(default=10)),
                ('items_in_page', models.PositiveIntegerField(default=10)),
                ('messages_in_chat_page', models.PositiveIntegerField(default=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
