# Generated by Django 3.0.3 on 2020-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member_of',
        ),
        migrations.AddField(
            model_name='profile',
            name='smember_of',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
