# Generated by Django 3.2 on 2023-09-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='beep_volume',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
