# Generated by Django 3.0.3 on 2020-02-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200217_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
