# Generated by Django 3.0.3 on 2020-02-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='members_of',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
