# Generated by Django 3.0.3 on 2020-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200217_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='members_of',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
