# Generated by Django 3.0.3 on 2020-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200217_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_level',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
