# Generated by Django 3.0.3 on 2021-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200520_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_rows',
            field=models.IntegerField(default=10),
        ),
    ]
