# Generated by Django 3.1 on 2021-09-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_list_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='members_of',
            new_name='club',
        ),
    ]
