# Generated by Django 3.1 on 2021-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210902_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='call',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
