# Generated by Django 3.1 on 2022-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220401_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_public',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
