# Generated by Django 3.1 on 2022-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20221014_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_chat',
            field=models.CharField(default='<p></p>', max_length=200),
        ),
    ]
