# Generated by Django 3.1 on 2021-09-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='post_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
