# Generated by Django 3.1 on 2021-09-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='origin_post_id',
            field=models.IntegerField(default=0),
        ),
    ]
