# Generated by Django 3.1 on 2021-09-24 15:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_post_origin_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
