# Generated by Django 3.1 on 2021-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210924_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_post',
            name='post_id',
        ),
        migrations.AddField(
            model_name='forum_post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
