# Generated by Django 3.1 on 2022-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210927_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
