# Generated by Django 3.1 on 2022-10-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20221014_1606'),
        ('chat', '0002_chat_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
